#!/usr/bin/env python

from stix.core import STIXPackage, STIXHeader
from cybox.core import Observable
from cybox.objects.address_object import Address, EmailAddress
from cybox.objects.file_object import File
from cybox.objects.hostname_object import Hostname
from cybox.objects.port_object import Port
from cybox.objects.uri_object import URI
from cybox.objects.user_account_object import UserAccount
import sys
import csv

if len(sys.argv) < 3 or len(sys.argv) > 4:
    print "Usage:"
    print "  create <input> <output> [<id>]"
    sys.exit(1)

input_file = sys.argv[1]
output_file = sys.argv[2]

if len(sys.argv) == 4:
    id = sys.argv[3]
else:
    id = None

def create_email_observable(pkg, id, description, email):
    a = EmailAddress("bunchy@email.com")
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_ipv4_observable(pkg, id, description, ip):
    a = Address(ip, Address.CAT_IPV4)
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_mac_observable(pkg, id, description, mac):
    a = Address(mac, Address.CAT_MAC)
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_file_observable(pkg, id, description, path, hash):
    a = File()
    if hash != "":
        a.add_hash(hash)
    if path != "":
        a.full_path = path
    a.md5 = True
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_hostname_observable(pkg, id, description, hostname):
    a = Hostname()
    a.hostname_value = hostname
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_port_observable(pkg, id, description, proto, port):
    a = Port()
    a.layer4_protocol = proto
    a.port_value = port
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_uri_observable(pkg, id, description, uri):
    a = URI(uri)
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

def create_user_account_observable(pkg, id, description, username, domain):
    a = UserAccount()
    a.username = username
    a.domain = domain
    o = Observable(a)
    o.id_ = id
    o.description = description
    pkg.add_observable(o)

header = STIXHeader()
header.description = "Getting Started!"
header.add_package_intent("Indicators - Watchlist")

package = STIXPackage()
package.stix_header = header
if id:
    package.id_ = id

input = open(input_file, 'r')
reader = csv.reader(input)
for row in reader:

    print ', '.join(row)

    id = row[0]
    del row[0]

    type = row[0]
    del row[0]

    description = row[0]
    del row[0]
    
    if type == 'email':
        create_email_observable(package, id, description, row[0])
    
    if type == 'ipv4':
        create_ipv4_observable(package, id, description, row[0])
    
    if type == 'mac':
        create_mac_observable(package, id, description, row[0])

    if type == 'file':
        create_file_observable(package, id, description, row[0], row[1])

    if type == 'hostname':
        create_hostname_observable(package, id, description, row[0])

    if type == 'port':
        create_port_observable(package, id, description, row[0], row[1])

    if type == 'uri':
        create_uri_observable(package, id, description, row[0])

    if type == 'user_account':
        create_user_account_observable(package, id, description, row[0], row[1])

f = open(output_file, 'w')
f.write('<?xml version="1.0"?>')
f.write(package.to_xml())
f.close()

sys.exit(0)

