#!/usr/bin/env python

import libtaxii as t
import libtaxii.messages_11 as tm11
import BaseHTTPServer
import time
from stix.core import STIXPackage, STIXHeader
import StringIO
import argparse
import libtaxii.taxii_default_query as tdq
from lxml import etree
import sys
import gmt
from stix_store import STIXStore
from taxii_server import TAXIIHandler, TAXIIServer

# Uses a directory containing STIX documents.  Directory structure is...
#   <data_dir/<collection>/<document>

str = []
############################################################################
# Request handler
############################################################################
class Handler(TAXIIHandler):

    def received(s, content, collection):

        # Hack XML header on.
#        content = "<?xml version=\"1.0\"?>\n" + content

        s.store.store(content, [collection])

    # Handling a TAXII PollRequest
    def get_matching(s, collection, begin, end, query, handle):
        return s.store.get_matching(collection, begin, end, query, handle)
        

############################################################################
# Main body
############################################################################

# Parse command line arguments
p = argparse.ArgumentParser(description="TAXII server")
p.add_argument("--host", dest="host", default="localhost", 
               help="Host to start the HTTP service on. "
               "Defaults to localhost.")
p.add_argument("--port", dest="port", default="8080", 
               help="Port where the Poll Service is hosted. Defaults to "
               "8080.")
p.add_argument("--data_dir", dest="data_dir", default="data/", 
               help="Directory where the STIX data is stored. Defaults to "
               "'data'.")
args = p.parse_args()

# FIXME: All round
Handler.store = STIXStore("FIXME.db")

# Construct HTTP server
server = TAXIIServer(args.host, int(args.port), Handler)
server.run()

