#!/usr/bin/env python3

import json
import sys
import os
import cyberprobe.qcomms as q
from cyberprobe.fsm import Fsm, FsmState, FsmCollection
import cyberprobe.indicators as ind
import cyberprobe.detector as detector

if len(sys.argv) < 2:
    binding = "geo"
else:
    binding = sys.argv[1]
    
if len(sys.argv) < 3:
    output = "ioc"
else:
    output = "ioc"

iocs_file = os.getenv("INDICATORS", "indicators.json")
mtime = 0

det = detector.Detector()

def check_config():

    global mtime
    global iocs
    global fsc
    
    s = os.stat(iocs_file).st_mtime
    if s == mtime: return

    print("Loading IOCs...")

    with open(iocs_file) as f:
        data = f.read()

    obj = json.loads(data)

    det.load(obj)
    
    print("Indicator data loaded.")
    mtime = s

def handle(msg, output):
    event = json.loads(msg)
    det.detect(event)
    output(json.dumps(event))

try:
    check_config()
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

q.subscribe(binding, handle, output)
