#!/usr/bin/env python3

import sys
import cyberprobe.indicators as ind

data = open(sys.argv[1]).read()
i = ind.loads(data)

ii = i.get(sys.argv[2])

fsm = ii.extract_fsm()

print('digraph g {')
print('graph [ pad="0.5", ranksep="1", nodesep="1" ]')

nodes = set()
    
for v in fsm:
    terms = [ "%s:%s" % (w[0], w[1]) for w in v[1] ]
    label = "\\n".join(terms)
    nodes.add(v[0])
    nodes.add(v[2])
    s = v[0].replace("-", "_")
    d = v[2].replace("-", "_")
    print('%s -> %s [label = "%s"];' % (s, d, label))

    for node in nodes:
        print('%s [label = "%s"];' % (node.replace("-", "_"), node))

print('}')



