#!/usr/bin/env python3

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pickle

with open("benchmark.pkl", "rb") as f:
    bench = pickle.load(f)


fig, ax = plt.subplots()

for v in bench:
    print(v)
    x = [w[0] for w in bench[v]]
    y = [w[2] for w in bench[v]]
    print(x, y)
    ax.plot(x, y,
            marker=".",
            label=v)

ax.legend()

ax.set(xlabel='rules', ylabel='detect rate',
       title='Detection rates')
ax.grid()

fig.savefig("plot.png")
plt.show()

