#!/usr/bin/env python3

import json
import sys
import cyberprobe.analytic as q
import cyberprobe.cyberprobe_pb2 as pb

if len(sys.argv) < 2:
    binding = "ioc"
else:
    binding = sys.argv[1]
    
def handle(msg, output):
    try:
        obj = pb.Event()
        obj.ParseFromString(msg.data())

        tm = obj.time.ToDatetime()

        if len(obj.indicators) > 0:
            print("%s, %s, %s" % (tm, obj.device, pb.Action.Name(obj.action)))
            for v in obj.indicators:
                print("  %s: %s" % (v.value, v.description))
            print()
    except Exception as e:
        print(e)

try:
    q.subscribe(binding, handle)
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

