#!/usr/bin/env python

import zmq
import json
import sys

if len(sys.argv) < 2:
    binding = "tcp://localhost:5555"
else:
    binding = sys.argv[1]
    
def handle(msg):
    if msg.has_key("indicators"):
        print "%s, %s, %s" % (msg["time"], msg["device"], msg["action"])
        for v in msg["indicators"]:
            print "  %s: %s" % (v["value"], v["description"])
        print

ctxt = zmq.Context()
skt = ctxt.socket(zmq.SUB)
skt.connect(binding)
skt.setsockopt(zmq.SUBSCRIBE, "")

while True:
    try:
        msg = skt.recv()
        handle(json.loads(msg))
    except Exception, e:
        sys.stderr.write("Exception: %s\n" % str(e))

