#!/usr/bin/env python3

import json
import sys
import cyberprobe.qcomms as q

if len(sys.argv) < 2:
    binding = "cyberprobe"
else:
    binding = sys.argv[1]
    
def handle(msg, output):
    print(msg.decode("utf-8"))

try:
    q.subscribe(binding, handle)
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

