#!/usr/bin/env python3

import json
import sys
import cyberprobe.qcomms as q

if len(sys.argv) < 2:
    binding = "ioc"
else:
    binding = sys.argv[1]
    
def handle(msg, output):
    obj = json.loads(msg)
    if obj.has_key("indicators"):
        print("%s, %s, %s" % (obj["time"], obj["device"], obj["action"]))
        for v in obj["indicators"]:
            print("  %s: %s" % (v["value"], v["description"]))
        print

try:
    q.subscribe(binding, handle)
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

