#!/usr/bin/env python3

import json
import sys
import cyberprobe.analytic as q
import cyberprobe.cyberprobe_pb2 as pb
from google.protobuf.json_format import MessageToJson

if len(sys.argv) < 2:
    binding = "cyberprobe"
else:
    binding = sys.argv[1]
    
def handle(msg, output):
    ev = pb.Event()
    ev.ParseFromString(msg.data())
    data = MessageToJson(ev)
    data = json.dumps(json.loads(data))
    print(data)

try:
    q.subscribe(binding, handle)
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

