#!/usr/bin/env python3

import json
import sys
import cyberprobe.qcomms as q

if len(sys.argv) < 2:
    binding = "cyberprobe"
else:
    binding = sys.argv[1]
    
def handle(msg, output):

    obj = json.loads(msg)

    print()
    print("Action: %s" % obj["action"])
    print("Device: %s" % obj["device"])

    print("Time: %s" % obj["time"])

    if "url" not in obj:
        print("URL: %s" % obj["url"])

    if "icmp" not in obj:
        print("ICMP type: %d" % obj["icmp"]["type"])
        print("ICMP code: %d" % obj["icmp"]["code"])

    if "dns_message" not in obj:
        detail = obj["dns_message"]
        if "type" in detail:
            print("Type: %s" % detail["type"])
            if detail["type"] == "query" and "query" in detail:
                for v in detail["query"]:
                    if "name" in v:
                        print("Query name: %s" % v["name"])
                    if "type" in v:
                        print("Query type: %s" % v["type"])
                    if "class" in v:
                        print("Query class: %s" % v["class"])
            if "answer" in detail:
                for v in detail["answer"]:
                    if "name" in v:
                        print("Answer name: %s" % v["name"])
                    if "type" in v:
                        print("Answer type: %s" % v["type"])
                    if "class" in v:
                        print("Answer class: %s" % v["class"])
                    if "address" in v:
                        print("Answer address: %s" % v["address"])

    if "http_request" in obj:
        detail = obj["http_request"]
        print("Method: %s" % detail["method"])
        if "header" in detail:
            for k in detail["header"]:
                 print("%s: %s" % (k, detail["header"][k]))

    if "http_response" in obj:
        detail = obj["http_response"]
        print("Code: %d" % detail["code"])
        print("Status: %s" % detail["status"])
        if "header" in detail:
            for k in detail["header"]:
                 print("%s: %s" % (k, detail["header"][k]))

    if "ftp_command" in obj:
        detail = obj["ftp_command"]
        print("Command: %s" % detail["command"])

    if "ftp_response" in obj:
        detail = obj["ftp_response"]
        print("Status: %d" % detail["status"])
        for v in detail["text"]:
            print("Text: %s" % v)

    if "sip_request" in obj:
        detail = obj["sip_request"]
        print("Method: %s" % detail["method"])
        print("From: %s" % detail["from"])
        print("To: %s" % detail["from"])
        if "header" in detail:
            for k in detail["header"]:
                 print("%s: %s" % (k, detail["header"][k]))

    if "sip_response" in obj:
        detail = obj["sip_response"]
        print("Code: %d" % detail["code"])
        print("Status: %s" % detail["status"])
        print("From: %s" % detail["from"])
        print("To: %s" % detail["from"])

    if "smtp_command" in obj:
        detail = obj["smtp_command"]
        print("Command: %s" % detail["command"])

    if "smtp_response" in obj:
        detail = obj["smtp_response"]
        print("Status: %d" % detail["status"])
        for v in detail["text"]:
            print("Text: %s" % v)

try:
    q.subscribe(binding, handle)
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

