#!/usr/bin/env python3

import json
import sys
import requests
import time
import cyberprobe.qcomms as q

############################################################################

if len(sys.argv) < 2:
    binding = "ioc"
else:
    binding = sys.argv[1]
    
if len(sys.argv) < 3:
    es_url = "http://localhost:9200/"
else:
    es_url = sys.argv[2]

es_index = "cyberprobe"

############################################################################

def init():

    mapping = {
        "mappings": {
            "properties": {
		"id": { "type": "keyword" },
		"time": { "type": "date" },
		"url": { "type": "keyword" },
		"action": { "type": "keyword" },
		"device": { "type": "keyword" },
		"network": { "type": "keyword" },
		"dns": {
		    "properties": {
		        "type": {
		            "type": "keyword"
		        },
                        "query": {
		            "properties": {
		                "name": {
		                    "type": "keyword"
		                },
		                "type": {
		                    "type": "keyword"
		                },
		                "class": {
		                    "type": "keyword"
		                }
		            }
		        },
		        "answer": {
		            "properties": {
		                "name": {
		                    "type": "keyword"
		                },
		                "type": {
		                    "type": "keyword"
		                },
		                "class": {
		                    "type": "keyword"
		                },
		                "address": {
		                    "type": "keyword"
		                }
		            }
		        }
		    }
		},
		"http": {
		    "properties": {
		        "method": {
		            "type": "keyword"
		        },
		        "status": {
		            "type": "keyword"
		        },
		        "code": {
		            "type": "integer"
		        },
		        "header": {
		            "properties": {
		                "User-Agent": {
		                    "type": "keyword"
		                },
		                "Host": {
		                    "type": "keyword"
		                },
		                "Content-Type": {
		                    "type": "keyword"
		                },
		                "Server": {
		                    "type": "keyword"
		                },
		                "Connection": {
		                    "type": "keyword"
		                }
		            }
		        }
		    }
		},
		"ftp": {
		    "properties": {
		        "command": {
		            "type": "keyword"
		        },
		        "status": {
		            "type": "integer"
		        },
		        "text": {
		            "type": "text"
		        }
		    }
		},
		"icmp": {
		    "properties": {
		        "type": {
		            "type": "integer"
		        },
		        "code": {
		            "type": "integer"
		        }
		    }
		},
		"sip": {
		    "properties": {
		        "method": {
		            "type": "keyword"
		        },
		        "from": {
		            "type": "keyword"
		        },
		        "to": {
		            "type": "keyword"
		        },
		        "status": {
		            "type": "keyword"
		        },
		        "code": {
		            "type": "integer"
		        }
		    }
		},
		"smtp": {
		    "properties": {
		        "command": {
		            "type": "keyword"
		        },
		        "from": {
		            "type": "keyword"
		        },
		        "to": {
		            "type": "keyword"
		        },
		        "status": {
		            "type": "keyword"
		        },
		        "text": {
		            "type": "text"
		        },
		        "code": {
		            "type": "integer"
		        }
		    }
		},
		"ntp": {
		    "properties": {
		        "version": {
		            "type": "integer"
		        },
		        "mode": {
		            "type": "integer"
		        }
		    }
		},
		"src": {
		    "properties": {
		        "ipv4": {
		            "type": "ip"
		        },
		        "ipv6": {
		            "type": "ip"
		        },
		        "tcp": {
		            "type": "integer"
		        },
		        "udp": {
		            "type": "integer"
		        }
		    }
		},
		"dest": {
		    "properties": {
		        "ipv4": {
		            "type": "ip"
		        },
		        "ipv6": {
		            "type": "ip"
		        },
		        "tcp": {
		            "type": "integer"
		        },
		        "udp": {
		            "type": "integer"
		        }
		    }
		},
		"location": {
		    "properties": {
		        "src": {
		            "properties": {
		                "city": {
		                    "type": "keyword"
		                },
		                "iso": {
		                    "type": "keyword"
		                },
		                "country": {
		                    "type": "keyword"
		                },
		                "asnum": {
		                    "type": "integer"
		                },
		                "asorg": {
		                    "type": "keyword"
		                },
		                "position": {
		                    "type": "geo_point"
		                },
		                "accuracy": {
		                    "type": "integer"
		                },
		                "postcode": {
		                    "type": "keyword"
		                }
		            }
		        },
		        "dest": {
		            "properties": {
		                "city": {
		                    "type": "keyword"
		                },
		                "iso": {
		                    "type": "keyword"
		                },
		                "country": {
		                    "type": "keyword"
		                },
		                "asnum": {
		                    "type": "integer"
		                },
		                "asorg": {
		                    "type": "keyword"
		                },
		                "position": {
		                    "type": "geo_point"
		                },
		                "accuracy": {
		                    "type": "integer"
		                },
		                "postcode": {
		                    "type": "keyword"
		                }
		            }
		        }
		    }
		},
		"indicators": {
		    "properties": {
		        "id": {
		            "type": "keyword"
		        },
		        "type": {
		            "type": "keyword"
		        },
		        "value": {
		            "type": "keyword"
		        },
		        "description": {
		            "type": "keyword"
		        },
		        "category": {
		            "type": "keyword"
		        },
		        "author": {
		            "type": "keyword"
		        },
		        "source": {
		            "type": "keyword"
		        }
		    }
		}
	    }
	}
    }

    u = "%s%s" % (es_url, es_index)

    while True:
        try: 
            r = requests.put(u, data=json.dumps(mapping),
                             headers={"Content-Type": "application/json"})
            if r.status_code != 201 and r.status_code != 200 and r.status_code != 400:
                sys.stderr.write("elasticsearch: Error sending to ElasticSearch\n")
                sys.stderr.write("elasticsearch: HTTP code: " + str(r.status_code) + "\n")
                print(r.text)
            sys.stderr.write("elasticsearch: Mapping put: %d\n" % r.status_code)
            break
        except Exception as e:
            sys.stderr.write("elasticsearch: Exception: %s\n" % str(e))
            time.sleep(1)

def es_output(obs, id):

    u = "%s%s/_doc/%s" % (es_url, es_index, id)

    r = requests.put(u, data=json.dumps(obs),
                     headers={"Content-Type": "application/json"})
    if r.status_code != 201:
        print(obs)
        print("Error sending to ElasticSearch")
        print("HTTP code: " + str(r.status_code))

        print(r.text)

############################################################################

def handle(msg, output):

    ev = json.loads(msg)

    ob = {}
    ob["id"] = ev["id"]
    ob["action"] = ev["action"]
    ob["device"] = ev["device"]
    try:
        ob["network"] = ev["network"]
    except:
        pass
    ob["time"] = ev["time"]
    if "url" in ev: ob["url"] = ev["url"]
    if "location" in ev: ob["location"] = ev["location"]
        
    if "dns_message" in ev:

        ob["dns"] = {}

        if "query" in ev["dns_message"]:

            name = []
            tpe = []
            clss = []

            for v in ev["dns_message"]["query"]:
                if "name" in v: name.append(v["name"])
                if "type" in v: tpe.append(v["type"])
                if "class" in v: clss.append(v["class"])

            ob["dns"]["query"] = {
                "name": name, "type": tpe, "class": clss
            }

        if "answer" in ev["dns_message"]:

            name = []
            tpe = []
            clss = []
            address = []

            for v in ev["dns_message"]["answer"]:
                if "name" in v: name.append(v["name"])
                if "type" in v: tpe.append(v["type"])
                if "class" in v: clss.append(v["class"])
                if "address" in v: address.append(v["address"])

            ob["dns"]["answer"] = {
                "name": name, "type": tpe, "class": clss, "address": address
            }

            ob["dns"]["type"] = ev["dns_message"]["type"]

    if "indicators" in ev:

        tpe = []
        id = []
        value = []
        desc = []

        for v in ev["indicators"]:
            tpe.append(v["type"])
            id.append(v["id"])
            value.append(v["value"])
            desc.append(v["description"])

        ob["indicators"] = {
            "type": tpe,
            "id": id,
            "value": value,
            "description": desc
        }

    if "http_request" in ev:
        ob["http"] = {
            "method": ev["http_request"]["method"],
            "header": ev["http_request"]["header"]
        }

    if "http_response" in ev:
        ob["http"] = {
            "status": ev["http_response"]["status"],
            "code": ev["http_response"]["code"],
            "header": ev["http_response"]["header"]
        }

    if "ftp_request" in ev:
        ob["ftp"] = {
            "command": ev["ftp_request"]["command"]
        }

    if "ftp_response" in ev:
        ob["ftp"] = {
            "status": ev["ftp_response"]["status"],
            "text": ev["ftp_response"]["text"]
        }

    if "icmp" in ev:
        ob["icmp"] = {
            "type": ev["icmp"]["type"],
            "code": ev["icmp"]["code"]
        }

    if "sip_request" in ev:
        ob["sip"] = {
            "method": ev["sip_request"]["method"],
            "from": ev["sip_request"]["from"],
            "to": ev["sip_request"]["to"]
        }

    if "sip_response" in ev:
        ob["sip"] = {
            "code": ev["sip_response"]["code"],
            "status": ev["sip_response"]["status"],
            "from": ev["sip_response"]["from"],
            "to": ev["sip_response"]["to"]
        }

    if "smtp_command" in ev:
        ob["smtp"] = {
            "command": ev["smtp_command"]["command"]
        }

    if "smtp_response" in ev:
        ob["smtp"] = {
            "status": ev["smtp_response"]["status"],
            "text": ev["smtp_response"]["text"]
        }

    if "smtp_data" in ev:
        ob["smtp"] = {
            "from": ev["smtp_data"]["from"],
            "to": ev["smtp_data"]["to"]
        }

    if "ntp_timestamp" in ev:
        ob["ntp"] = {
            "version": ev["ntp_timestamp"]["version"],
            "mode": ev["ntp_timestamp"]["mode"]
        }

    if "ntp_control" in ev:
        ob["ntp"] = {
            "version": ev["ntp_control"]["version"],
            "mode": ev["ntp_control"]["mode"]
        }

    if "ntp_private" in ev:
        ob["ntp"] = {
            "version": ev["ntp_private"]["version"],
            "mode": ev["ntp_private"]["mode"]
        }

    src = {}

    if "src" in ev:
        for v in ev["src"]:
            if v.find(":") < 0:
                cls = v
                addr = ""
            else:
                cls = v[0:v.find(":")]
                addr = v[v.find(":") + 1:]

            if cls not in src:
                src[cls] = []

            src[cls].append(addr)

        ob["src"] = src

    dest = {}

    if "dest" in ev:
        for v in ev["dest"]:
            if v.find(":") < 0:
                cls = v
                addr = ""
            else:
                cls = v[0:v.find(":")]
                addr = v[v.find(":") + 1:]

            if cls not in dest:
                dest[cls] = []

            dest[cls].append(addr)

        ob["dest"] = dest

    es_output(ob, ev["id"])

############################################################################

print("Connecting to ElasticSearch...")
while True:
    url = es_url
    try:
        r = requests.get(url)
    except:
        print("Not connected, will retry...")
        time.sleep(10)
        continue

    if r.status_code == 200: break

    print("Not connected, will retry...")
    time.sleep(10)

print("Connected.")

init()

try:
    q.subscribe(binding, handle)
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

