#!/usr/bin/env python3

import sys
import cyberprobe.analytic as q
import cyberprobe.cyberprobe_pb2 as pb

if len(sys.argv) < 2:
    binding = "ioc"
else:
    binding = sys.argv[1]

class Alerter(q.EventAnalytic):
    def event(self, ev, properties):

        tm = ev.time.ToDatetime()

        if len(ev.indicators) > 0:
            print("%s, %s, %s" %
                  (tm, ev.device, pb.Action.Name(ev.action)))
            for v in ev.indicators:
                print("  %s: %s" % (v.value, v.description))
            print()

try:
    Alerter(binding).run()
except Exception as e:
    sys.stderr.write("Exception: %s\n" % str(e))

