#!/usr/bin/env python3

from cyberprobe.fsm import Fsm, FsmState
import cyberprobe.indicators as ind
import json

with open("indicators.json") as f:
    data = f.read()

obj = json.loads(data)

i = ind.load(obj)
ii = i.indicators[6]

f = Fsm.load_from(ii)
print("FSM:")
f.dump()
print()

inits = f.get_activator_terms()
print("Inits:")
for init in inits:
    print("  - %s:%s" % (init[0], init[1]))
print()

print("Test case 1")
state = f.init_state()
terms = [
    ('url', 'http://malware.com/malware.dat'),
    ('bunchy', 'BUNCHY'),
    ('port', '224')
]
for v in terms:
    print(v)
    state.update(v)
print()

print("Test case 2")
state = f.init_state()
terms = [
    ('url', 'http://malware.com/malware.dat'),
    ('bunchy', 'BUNCHY'),
    ('end', '')
]
for v in terms:
    print(v)
    state.update(v)
print()

print("Test case 3")
state = f.init_state()
terms = [
    ('bunchy', 'BUNCHY'),
    ('end', '')
]
for v in terms:
    print(v)
    state.update(v)
print()

print("Test case 4")
state = f.init_state()
terms = [
    ('bunchy', 'BUNCHY'),
    ('port', '224'),
    ('end', '')
]
for v in terms:
    print(v)
    state.update(v)
print()

