\input texinfo   @c -*-texinfo-*-

@comment $Id@w{$}
@comment %**start of header
@setfilename cyberprobe.info
@include version.texi
@include paths.texi

@settitle Cyberprobe @value{VERSION}
@syncodeindex pg cp
@paragraphindent 0
@comment %**end of header

@copying
This manual is for Cyberprobe (version @value{VERSION}, @value{UPDATED}),
which is an example in the Texinfo documentation.

Copyright @copyright{} 2013-2014 Cyber MacGeddon

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.
@end quotation
@end copying

@dircategory Texinfo documentation system
@direntry
* overview: (overview)Overview.
@end direntry

@titlepage
@title Cyberprobe
@subtitle for version @value{VERSION}, @value{UPDATED}
@author cybermaggedon
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@comment ----------------------------------------------------------------------

@include top.texi

@comment ----------------------------------------------------------------------

@include overview.texi

@comment ----------------------------------------------------------------------

@include obtaining.texi

@comment ----------------------------------------------------------------------

@include qs-top.texi

@comment ----------------------------------------------------------------------

@include qs-preparation.texi

@comment ----------------------------------------------------------------------

@include qs-cyberprobe.texi

@comment ----------------------------------------------------------------------

@include qs-mgmt-if.texi

@comment ----------------------------------------------------------------------

@include qs-snort.texi

@comment ----------------------------------------------------------------------

@include qs-cybermon.texi

@comment ----------------------------------------------------------------------

@include qs-cybermon-config.texi

@comment ----------------------------------------------------------------------

@include qs-visualisation.texi

@comment ----------------------------------------------------------------------

@include qs-threat-indicators.texi

@comment ----------------------------------------------------------------------

@include cyberprobe-boot.texi

@comment ----------------------------------------------------------------------

@include pubsub.texi

@comment ----------------------------------------------------------------------

@include containerisation.texi

@comment ----------------------------------------------------------------------

@include aws-mirroring.texi

@comment ----------------------------------------------------------------------

@include dag.texi

@comment ----------------------------------------------------------------------

@include ref-top.texi

@comment ----------------------------------------------------------------------

@include ref-cyberprobe-invocation.texi

@comment ----------------------------------------------------------------------

@include ref-cyberprobe-config.texi

@comment ----------------------------------------------------------------------

@include ref-cyberprobe-cli-invocation.texi

@comment ----------------------------------------------------------------------

@include ref-cyberprobe-cli-commands.texi

@comment ----------------------------------------------------------------------

@include ref-streaming-protocols.texi

@comment ----------------------------------------------------------------------

@include ref-mgmt-protocol.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-invocation.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-configuration.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-example-configs.texi

@comment ----------------------------------------------------------------------

@include ref-json-event-format.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-monitor.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-elasticsearch.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-bigquery.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-gaffer.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-cassandra.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-geoip.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-detector.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-dump.texi

@comment ----------------------------------------------------------------------

@include ref-cybermon-alert.texi

@comment ----------------------------------------------------------------------

@include ref-taxii-client.texi

@comment ----------------------------------------------------------------------

@include ref-taxii-sync-json.texi

@comment ----------------------------------------------------------------------

@include ref-taxii-server.texi

@comment ----------------------------------------------------------------------

@include ref-nhis11-rcvr.texi

@comment ----------------------------------------------------------------------

@include ref-etsi-rcvr.texi

@comment ----------------------------------------------------------------------

@include ref-elasticsearch-model.texi

@comment ----------------------------------------------------------------------

@include architecture.texi

@comment ----------------------------------------------------------------------

@node Index
@unnumbered Index

@printindex cp

@bye

