
@node Quick start tutorial
@chapter Quick start tutorial
@cindex Getting started


@menu
* Preparation::
* Using @command{cyberprobe}::
* Management interface::
* Integration with @command{snort}::
* Using @command{cybermon}::
* Writing your own configuration file::
* Visualisation::
* Threat indicators::
@end menu
