
@node @command{evs-alert} invocation
@section @command{evs-alert} invocation

@cindex @command{evs-alert}, invocation
@cindex Alert

@command{evs-alert} subscribes to a pub/sub topic for
@command{cybermon} events, and outputs a human-readable message
when an IOC hits.

Synopsis:

@example
evs-alert [BINDING]
@end example

Example:
@example
evs-alert
evs-alert ioc
@end example

@table @samp

@item BINDING
Specifies the pub/sub topic to connect to.  If not specified, defaults
to @samp{ioc}.

@end table
