
@node @command{cybermon-geoip} invocation
@section @command{cybermon-geoip} invocation

@cindex @command{cybermon-geoip}, invocation
@cindex GeoIP

@command{cybermon-geoip} subscribes to a pub/sub queue for
@command{cybermon} events, adds location information from GeoIP, and
re-publishes the elaborated events.  This effectively creates a processing
chain.  The event subscription and publishing events should be different in
order to avoid creating an infinite loop.

Synopsis:

@example
cybermon-geoip [BINDING [PUBLICATION] ]
@end example

Example:
@example
cybermon-geoip
cybermon-geoip cyberprobe geo
@end example

@table @samp

@item BINDING
Specifies the pub/sub queue to connect to.  If not specified, defaults
to @samp{cyberprobe}.

@item PUBLICATION
Specifies the pub/sub queue to publish to.  If not specified, defaults
to @samp{geo}.

@end table
