
@node @command{evs-elasticsearch} invocation
@section @command{evs-elasticsearch} invocation

@cindex @command{evs-elasticsearch}, invocation

@command{evs-elasticsearch} subscribes to a pub/sub topic for
@command{cybermon}
events, and upon receipt of events, formats them for delivery to an
ElasticSearch store.

Synopsis:

@example
evs-elasticsearch [BINDING [ELASTICSEARCH-URL] ]
@end example

Example:
@example
evs-elasticsearch
evs-elasticsearch ioc http://elastic-store:9200/
@end example

@table @samp

@item BINDING
Specifies the pub/sub topic to connect to.  If not specified, defaults
to @samp{ioc}.

@item ELASTICSEARCH-URL
Specifies the base URL for ElasticSearch.  If not specified, defaults
to @samp{http://localhost:9200}.

@end table
