
@node @command{cybermon-monitor} invocation
@section @command{cybermon-monitor} invocation

@cindex @command{cybermon-monitor}, invocation

@command{cybermon-monitor} subscribes to a pub/sub topic for
@command{cybermon}
events, and upon receipt of events, formats them for output in a human-readable
manner.

Synopsis:

@example
cybermon-monitor [BINDING]
@end example

Example:
@example
cybermon-monitor
cybermon-monitor cyberprobe
@end example

@table @samp

@item BINDING
Specifies the pub/sub topic to connect to.  If not specified, defaults
to @samp{cyberprobe}.

@end table
