
@node @command{evs-dump} invocation
@section @command{evs-dump} invocation

@cindex @command{evs-dump}, invocation
@cindex JSON
@cindex Cybermon JSON message format

@command{evs-dump} subscribes to a pub/sub topic for
@command{cybermon} events, and dumps the raw JSON to standard output.

Synopsis:

@example
evs-dump [BINDING]
@end example

Example:
@example
evs-dump
evs-dump cyberprobe
@end example

@table @samp

@item BINDING
Specifies the pub/sub topic to connect to.  If not specified, defaults
to @samp{cyberprobe}.

@end table
