
@node @command{evs-detector} invocation
@section @command{evs-detector} invocation

@cindex @command{evs-detector}, invocation
@cindex IOC
@cindex Indicator of compromise
@cindex Indicator

@command{evs-detector} subscribes to a pub/sub topic for
@command{cybermon} events, inspects them for IOCs, and adds detection
information if IOCs are observed before re-publishing
the elaborated events.  This effectively creates a processing
chain.  The event subscription and publishing events should be different in
order to avoid creating an infinite loop.

The indicator file is specified by the @samp{INDICATORS} environment variable,
the default is @file{indicators.json}.  The file format is the
@ref{Cyberprobe indicator format}.  When the file changes, the indicators are
reloaded without the needed to restart @command{evs-detector}.

Synopsis:

@example
evs-detector [BINDING [PUBLICATION] ]
@end example

Example:
@example
evs-detector
evs-detector geo ioc
@end example

@table @samp

@item BINDING
Specifies the pub/sub topic to connect to.  If not specified, defaults
to @samp{geo}.

@item PUBLICATION
Specifies the pub/sub topic to publish to.  If not specified, defaults
to @samp{ioc}.

@end table

