
@node @command{evs-geoip} invocation
@section @command{evs-geoip} invocation

@cindex @command{evs-geoip}, invocation
@cindex GeoIP

@command{evs-geoip} subscribes to a pub/sub topic for
@command{cybermon} events, adds location information from GeoIP, and
re-publishes the elaborated events.  This effectively creates a processing
chain.  The event subscription and publishing events should be different in
order to avoid creating an infinite loop.

Synopsis:

@example
evs-geoip [BINDING [PUBLICATION] ]
@end example

Example:
@example
evs-geoip
evs-geoip cyberprobe geo
@end example

@table @samp

@item BINDING
Specifies the pub/sub topic to connect to.  If not specified, defaults
to @samp{cyberprobe}.

@item PUBLICATION
Specifies the pub/sub topic to publish to.  If not specified, defaults
to @samp{geo}.

@end table
