
@node @command{cybermon-bigquery} invocation
@section @command{cybermon-bigquery} invocation

@cindex @command{cybermon-bigquery}, invocation

@command{cybermon-bigquery} subscribes to a RabbitMQ pub/sub queue for
@command{cybermon}
events, and upon receipt of events, formats them for delivery to a Google
BigQuery table.

Synopsis:

@example
cybermon-bigquery [BINDING [KEY-FILE [PROJECT [DATASET [TABLE] ] ] ] ]
@end example

Example:
@example
cybermon-bigquery
cybermon-bigquery ioc /priv.json
@end example

@table @samp

@item BINDING
Specifies the RabbitMQ pub/sub queue to connect to.  If not specified, defaults
to @samp{ioc}.

@item KEY-FILE
Specifies the path to a Google cloud key file in 'private JSON' format.
If not specified, defaults
to @file{/etc/cyberprobe/private.json}.

@item PROJECT
Specifies the Google Cloud project ID to use.  Defaults to the project ID
specified in the private JSON key file.

@item DATASET
Specifies the BigQuery data set, defaults to @samp{cyberprobe}.  You need to
create this dataset, it is not created for you.

@item TABLE
Specifies the BigQuery table within the dataset.  This is created if it does
not already exist.  Don't try to create this yourself, if you use the wrong
schema, data won't load correctly.

@end table

